#%RAML 1.0 SecurityScheme
type: OAuth 2.0
description: |
  Autenticação sistema-a-sistema. O chamador (BANCO ou Mobile
  Money) obtém um token com as suas credenciais de cliente OAuth2.
describedBy:
  headers:
    Authorization:
      description: Bearer token OAuth2
      type: string
      example: "Bearer eyJhbGciOiJSUzI1NiIs..."
  responses:
    401:
      description: Token ausente, inválido ou expirado
      body:
        application/json:
          type: !include ../types/erro.raml
    403:
      description: Token válido, mas sem o scope necessário para esta operação
      body:
        application/json:
          type: !include ../types/erro.raml
settings:
  accessTokenUri: https://auth.pay.ao/oauth2/token
  authorizationGrants: [client_credentials]
  scopes:
    - payment-instruction:write
    - payment-instruction:read
    - reversals:write