#%RAML 1.0 Trait
description: Aplica um limite de requisições por instituição parceira.
responses:
  429:
    description: Limite de pedidos excedido para este cliente.
    headers:
      Retry-After:
        description: Segundos até ser possível tentar novamente
        type: integer
    body:
      application/json:
        type: !include ../types/erro.raml
        